version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: magic_book_store
